version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge